// export default {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };
export default {
  login: "feelchi1star",
  id: 70848994,
  node_id: "MDQ6VXNlcjcwODQ4OTk0",
  avatar_url: "https://avatars.githubusercontent.com/u/70848994?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/feelchi1star",
  html_url: "https://github.com/feelchi1star",
  followers_url: "https://api.github.com/users/feelchi1star/followers",
  following_url:
    "https://api.github.com/users/feelchi1star/following{/other_user}",
  gists_url: "https://api.github.com/users/feelchi1star/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/feelchi1star/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/feelchi1star/subscriptions",
  organizations_url: "https://api.github.com/users/feelchi1star/orgs",
  repos_url: "https://api.github.com/users/feelchi1star/repos",
  events_url: "https://api.github.com/users/feelchi1star/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/feelchi1star/received_events",
  type: "User",
  site_admin: false,
  name: "Felix Chinonso Emmanuel",
  company: null,
  blog: "www.feelchi1star.com",
  location: null,
  email: null,
  hireable: true,
  bio: null,
  twitter_username: "feelchi1starcom",
  public_repos: 21,
  public_gists: 0,
  followers: 1,
  following: 12,
  created_at: "2020-09-06T13:47:06Z",
  updated_at: "2022-08-06T17:24:49Z",
};
